# Generated by Django 5.1.6 on 2025-02-18 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaler', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
